- name: redis group
  group: name=redis state=present

- name: redis user
  user: name=redis group=redis state=present

- name: redis install directory
  file: path={{redis_install_directory}} state=directory mode=0755

- name: redis conf directory
  file: path={{redis_conf_directory}} state=directory mode=0755

- name: redis log directory
  file: path={{redis_log_directory}} state=directory mode=0755 owner=redis group=redis

- name: redis files directory
  file: path={{redis_files_directory}}/{{redis_port}} state=directory mode=0755 owner=redis group=redis

- name: download redis
  get_url: url={{redis_download_url}}/redis-{{redis_version}}.tar.gz dest={{redis_install_directory}}/redis-{{redis_version}}.tar.gz mode=0440

- name: unpack redis
  unarchive: src={{redis_install_directory}}/redis-{{redis_version}}.tar.gz dest={{redis_install_directory}} copy=no

- name: make redis
  command: make chdir={{redis_install_directory}}/redis-{{redis_version}} creates={{redis_install_directory}}/redis-{{redis_version}}/src/redis-server

- name: install redis
  command: make install chdir={{redis_install_directory}}/redis-{{redis_version}} creates=/usr/local/bin/redis-server

- name: redis init script
  template: src=redis-upstart.conf dest={{redis_init_script_path}}

- name: symlink at /etc/init.d/redis-server
  file: src={{redis_init_script_path}} dest=/etc/init.d/redis-server state=link

- name: redis conf file
  template: src=redis.conf dest={{redis_conf_directory}}/{{redis_port}}.conf
  notify: restart redis
